import { EducationCategory, type EducationType } from '../types/education.types';

export const EDUCATION: EducationType[] = [
  {
    category: EducationCategory.GENERAL,
    school: 'Komarovi Physics and Mathematics School',
    degree: 'High School Diploma',
    date: '2014 - 2020',
    logoPath: '/images/education/komarovi-logo.png',
    borderColor: 'border-[#2ab1e0]',
  },
  {
    category: EducationCategory.GENERAL,
    school: 'Mziuri Collage',
    degree: 'Programming Basics and C++',
    date: '2018-2020',
    logoPath: '/images/education/mziuri-logo.png',
    borderColor: 'border-[#253c4c]',
  },
  {
    category: EducationCategory.GENERAL,
    school: 'Free University of Tbilisi',
    degree: 'Computer Science and Mathematics (Bachelor)',
    date: '2020 - Present',
    logoPath: '/images/education/freeuni-logo.png',
    borderColor: 'border-[#ffd100]',
  },
  {
    category: EducationCategory.CERTIFICATIONS,
    school: 'New Horizons',
    degree: 'Back-end Programming',
    certificateLink: 'https://drive.google.com/file/d/1jzVUWnNvXph2hE86wspF9wQ486Vwp0nd/view?usp=sharing',
    date: '2022',
    logoPath: '/images/education/new-horizons-logo.png',
    borderColor: 'border-[#2c2a6b]',
  },
  {
    category: EducationCategory.CERTIFICATIONS,
    school: 'New Horizons',
    degree: 'Blockchain Development',
    certificateLink: 'https://drive.google.com/file/d/1oltkp8v3VUO8HX6hsZrGstoAjNWK0MV2/view?usp=sharing',
    date: '2023',
    logoPath: '/images/education/new-horizons-logo.png',
    borderColor: 'border-[#2c2a6b]',
  },
  {
    category: EducationCategory.CERTIFICATIONS,
    school: 'Blockhain Training Alliance',
    degree: 'Blockchain Developer - Ethereum',
    certificateLink: 'https://drive.google.com/file/d/1qxP2r2w6wskiWN8iOLb-2l9dLIjs_qzf/view?usp=sharing',
    date: '2023',
    logoPath: '/images/education/bta-logo.png',
    borderColor: 'border-[#61378e]',
  },
  {
    category: EducationCategory.CERTIFICATIONS,
    school: 'Orient Logic Academy',
    degree: 'React Development',
    certificateLink: 'https://drive.google.com/file/d/1oSHynB7OPYA9vA1wK53x56ld5cQ8wWJY/view?usp=sharing',
    date: '2024',
    logoPath: '/images/education/ol-academy-logo.png',
    borderColor: 'border-[#04dffc]',
  },
];
