import { EducationCategory, type EducationType } from '../types/education.types';

export const EDUCATION: EducationType[] = [
  {
    category: EducationCategory.GENERAL,
    school: 'Komarovi Physics and Mathematics School',
    degree: 'High School Diploma',
    date: '2014 - 2020',
    logoPath: '/images/education/komarovi-logo.webp',
    websiteLink: 'https://komarovi.edu.ge/',
  },
  {
    category: EducationCategory.GENERAL,
    school: 'Mziuri Collage',
    degree: 'Programming Basics and C++',
    date: '2018-2020',
    logoPath: '/images/education/mziuri-logo.webp',
    websiteLink: 'https://www.mziuri.ge/',
  },
  {
    category: EducationCategory.GENERAL,
    school: 'Free University of Tbilisi',
    degree: 'Computer Science and Mathematics (Bachelor)',
    date: '2020 - Present',
    logoPath: '/images/education/freeuni-logo.webp',
    websiteLink: 'https://freeuni.edu.ge/',
  },
  {
    category: EducationCategory.CERTIFICATIONS,
    school: 'Cyfrin Updraft',
    degree: 'Blockchain Basics',
    certificateLink: 'https://drive.google.com/file/d/1KE1yl0zkwlFU5spRKV2U52QMSaUzEk1M/view?usp=sharing',
    date: '2025',
    logoPath: '/images/social/cyfrin.svg',
    websiteLink: 'https://updraft.cyfrin.io/',
  },
  {
    category: EducationCategory.CERTIFICATIONS,
    school: 'Blockhain Training Alliance',
    degree: 'Blockchain Developer - Ethereum',
    certificateLink: 'https://drive.google.com/file/d/1qxP2r2w6wskiWN8iOLb-2l9dLIjs_qzf/view?usp=sharing',
    date: '2023',
    logoPath: '/images/education/bta-logo.webp',
    websiteLink: 'https://blockchaintrainingalliance.com/',
  },
  {
    category: EducationCategory.CERTIFICATIONS,
    school: 'New Horizons',
    degree: 'Blockchain Development',
    certificateLink: 'https://drive.google.com/file/d/1oltkp8v3VUO8HX6hsZrGstoAjNWK0MV2/view?usp=sharing',
    date: '2023',
    logoPath: '/images/education/new-horizons-logo.webp',
    websiteLink: 'https://www.newhorizons.com/',
  },
  {
    category: EducationCategory.CERTIFICATIONS,
    school: 'Orient Logic Academy',
    degree: 'React Development',
    certificateLink: 'https://drive.google.com/file/d/1oSHynB7OPYA9vA1wK53x56ld5cQ8wWJY/view?usp=sharing',
    date: '2024',
    logoPath: '/images/education/ol-academy-logo.webp',
    websiteLink: 'https://www.olacademy.ge/',
  },
  {
    category: EducationCategory.CERTIFICATIONS,
    school: 'New Horizons',
    degree: 'Back-end Programming',
    certificateLink: 'https://drive.google.com/file/d/1jzVUWnNvXph2hE86wspF9wQ486Vwp0nd/view?usp=sharing',
    date: '2022',
    logoPath: '/images/education/new-horizons-logo.webp',
    websiteLink: 'https://www.newhorizons.com/',
  },
];
